- hosts: Movies_back_instance
  become: yes
  become_user: root
  become_method: sudo

  vars:
    app_name: appBack

  tasks:
    - name: include role docker
      include_role:
        name: docker
    - name: include role clear-container
      include_role:
        name: clear-container

    - name: Get env file
      fetch:
        src: /home/ubuntu/.container.env
        dest: /home/ubuntu/back.container.env
        flat: yes

    - name: Execute docker container
      docker_container:
        name: "{{ app_name }}"
        image: zeronetdev/rampup-back:{{ tag }}
        state: started
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - "3000:3000"
        env_file:
          - /home/ubuntu/.container.env