- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: install bastion required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: ['ansible', 'python3-pip', 'daemonize', 'mysql-client']
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10

    - name: copy private key
      copy:
        src: ~/.ssh/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        mode: '0400'

    - name: create symbolic link to python3
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link

    - name: install pip required libraries
      pip:
        name: "{{ item }}"
      loop: ['boto', 'boto3']

    - name: copy credentials
      copy:
        src: ~/.aws
        dest: /home/ubuntu/
        owner: ubuntu
        mode: '0600'

    - name: copy sql
      copy:
        src: ../files/schema.sql
        dest: /home/ubuntu/schema.sql
        owner: ubuntu
      become_user: ubuntu

    - name: provide db
      raw: "mysql --host={{ address }} --user=root --password={{ password }} < /home/ubuntu/schema.sql || true"

    - name: clone rampup
      git:
        repo: https://github.com/CarlosEduardoL/RampUp
        dest: /home/ubuntu/RampUp
        version: develop
      become_user: ubuntu

    - name: copy ansible config
      copy:
        src: ../ansible.cfg
        dest: /home/ubuntu/ansible.cfg
        owner: ubuntu
      become_user: ubuntu

    - name: copy provisioner server
      copy:
        src: ../files/provision_server
        dest: /root/provision_server
        mode: '0700'

    - name: run provisioner server
      raw: nohup /root/provision_server >/dev/null 2>&1 & sleep 1