- hosts: Movies_front_instance
  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - include_tasks: docker.yml

    - name: get info on frontend container
      docker_container_info:
        name: appFront
      register: result

    - name: Does container exists?
      ansible.builtin.debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Stop container
      docker_container:
        name: appFront
        state: stopped
      when: result.exists

    - name: Remove container
      docker_container:
        name: appFront
        state: absent

    - name: Remove image
      docker_image:
        state: absent
        name: appFront

    - name: Execute docker container
      docker_container:
        name: appFront
        image: zeronetdev/rampup-front:{{ tag }}
        state: started
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - "3030:3030"
        env: 
          BACK_HOST: '{{ back_host }}'